import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#061017',
  },
  pageSafeArea: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  homeContent: {
    flexGrow: 1,
    paddingBottom: 22,
  },
  overlaySafeArea: {
    flex: 1,
  },
  heroCard: {
    borderRadius: 8,
    padding: 18,
    backgroundColor: 'rgba(9, 18, 27, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(174, 228, 246, 0.10)',
    overflow: 'hidden',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    gap: 12,
  },
  heroTitle: {
    color: '#f4fbff',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    marginBottom: 6,
  },
  heroSubtitle: {
    color: 'rgba(219, 232, 240, 0.78)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  menuStack: {
    marginTop: 14,
    gap: 10,
  },
  menuCard: {
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: 'rgba(10, 19, 28, 0.92)',
    borderWidth: 1,
    minHeight: 112,
  },
  menuCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.992 }],
  },
  menuCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  menuCardIndex: {
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  menuCardAccent: {
    width: 44,
    height: 6,
    borderRadius: 6,
  },
  menuCardTitle: {
    color: '#f5fbff',
    fontSize: 21,
    lineHeight: 25,
    fontWeight: '800',
    marginBottom: 6,
  },
  menuCardSubtitle: {
    color: 'rgba(215, 231, 240, 0.74)',
    fontSize: 13,
    lineHeight: 18,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(7, 16, 22, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    flexShrink: 1,
    maxWidth: '66%',
  },
  liveBadgeMock: {
    backgroundColor: 'rgba(247,178,72,0.14)',
    borderColor: 'rgba(247,178,72,0.18)',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#7ef2ca',
  },
  liveDotMock: {
    backgroundColor: '#f7b248',
  },
  liveBadgeText: {
    color: '#f3fbff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
    flexShrink: 1,
  },
  expeditionTopBar: {
    paddingHorizontal: 12,
    paddingTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  torchButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 15, 22, 0.86)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  torchButtonActive: {
    backgroundColor: '#7ef2ca',
    borderColor: 'rgba(126,242,202,0.72)',
    shadowColor: '#7ef2ca',
    shadowOpacity: 0.34,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  torchButtonDisabled: {
    opacity: 0.42,
  },
  topActionButton: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(8, 15, 22, 0.86)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  topActionText: {
    color: '#eef9ff',
    fontSize: 13,
    fontWeight: '800',
  },
  headerCenterBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerEyebrow: {
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 3,
  },
  headerTitle: {
    color: '#f7fbff',
    fontSize: 18,
    fontWeight: '800',
    flexShrink: 1,
  },
  expeditionBottomWrap: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 0,
  },
  scannerDock: {
    borderRadius: 14,
    padding: 10,
    backgroundColor: 'rgba(6, 12, 17, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.12)',
  },
  scannerDockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  scannerDockTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  scannerDockEyebrow: {
    color: '#7ef2ca',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 4,
  },
  scannerDockTitle: {
    color: '#f5fbff',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
  },
  scannerDockMeta: {
    color: 'rgba(214, 229, 238, 0.76)',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 6,
  },
  scannerDockStats: {
    flexDirection: 'row',
    gap: 6,
    flexShrink: 0,
  },
  scannerDockStat: {
    minWidth: 48,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: 'rgba(126,242,202,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(126,242,202,0.18)',
  },
  scannerDockStatLabel: {
    color: 'rgba(214, 229, 238, 0.72)',
    fontSize: 9,
    fontWeight: '800',
    marginBottom: 1,
  },
  scannerDockStatValue: {
    color: '#f6fbff',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '900',
  },
  scannerDockActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 9,
  },
  selectedActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 9,
  },
  selectedAddButton: {
    flex: 1,
    minWidth: 0,
  },
  selectedClearButton: {
    width: 96,
    minWidth: 0,
    flexShrink: 0,
  },
  scannerDockButton: {
    minWidth: 126,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  flexButton: {
    flexGrow: 1,
    minWidth: 148,
  },
  primaryButton: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#7ef2ca',
  },
  primaryButtonDisabled: {
    opacity: 0.48,
  },
  primaryButtonText: {
    color: '#051c14',
    fontSize: 14,
    fontWeight: '900',
  },
  secondaryButton: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  secondaryButtonText: {
    color: '#eef8ff',
    fontSize: 14,
    fontWeight: '800',
  },
  ghostButton: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(211, 229, 239, 0.20)',
  },
  ghostButtonText: {
    color: '#d9ecf7',
    fontSize: 14,
    fontWeight: '700',
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  infoCard: {
    flex: 1,
    borderRadius: 22,
    padding: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  infoCardLabel: {
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 6,
  },
  infoCardValue: {
    color: '#eef9ff',
    fontSize: 13,
    lineHeight: 18,
  },
  scanListContent: {
    gap: 8,
    paddingTop: 9,
  },
  scanChip: {
    width: 148,
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(11, 20, 28, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
  },
  scanChipFormat: {
    color: '#7ef2ca',
    fontSize: 10,
    fontWeight: '800',
    marginBottom: 4,
  },
  scanChipText: {
    color: '#f6fbff',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 4,
  },
  scanChipMeta: {
    color: 'rgba(214, 229, 238, 0.72)',
    fontSize: 12,
    fontWeight: '700',
  },
  warmupBanner: {
    position: 'absolute',
    alignSelf: 'center',
    left: 18,
    right: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(7, 13, 18, 0.84)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  warmupBannerIssue: {
    backgroundColor: 'rgba(24, 10, 12, 0.92)',
    borderColor: 'rgba(255, 154, 154, 0.34)',
  },
  warmupTitle: {
    color: '#f7fbff',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  warmupText: {
    color: 'rgba(219,235,244,0.78)',
    fontSize: 12,
    marginTop: 2,
    textAlign: 'center',
  },
  warmupRetryButton: {
    alignSelf: 'center',
    marginTop: 10,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#ffd2d2',
  },
  warmupRetryButtonText: {
    color: '#2a0808',
    fontSize: 13,
    fontWeight: '900',
  },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 20,
  },
  pageHeaderTextWrap: {
    flex: 1,
  },
  pageEyebrow: {
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 6,
  },
  pageTitle: {
    color: '#f6fbff',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
  },
  overviewRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  overviewTile: {
    flex: 1,
    borderRadius: 24,
    padding: 14,
    backgroundColor: 'rgba(10, 19, 28, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
  },
  overviewLabel: {
    color: 'rgba(210, 229, 239, 0.72)',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
  },
  overviewValue: {
    color: '#f6fbff',
    fontSize: 17,
    fontWeight: '900',
  },
  archiveListContent: {
    paddingBottom: 28,
  },
  emptyStateCard: {
    borderRadius: 28,
    padding: 22,
    backgroundColor: 'rgba(10, 19, 28, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
  },
  emptyStateTitle: {
    color: '#f6fbff',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  emptyStateText: {
    color: 'rgba(214,229,238,0.76)',
    fontSize: 14,
    lineHeight: 20,
  },
  archiveCard: {
    borderRadius: 28,
    padding: 18,
    backgroundColor: 'rgba(10, 19, 28, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
    marginBottom: 12,
  },
  archiveCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  archiveCardTitle: {
    color: '#f5fbff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  archiveCardMeta: {
    color: 'rgba(214,229,238,0.64)',
    fontSize: 12,
    fontWeight: '700',
  },
  archiveBadge: {
    color: '#09170f',
    backgroundColor: '#7ef2ca',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    fontWeight: '900',
    alignSelf: 'flex-start',
  },
  archiveCardSummary: {
    color: 'rgba(214,229,238,0.76)',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 14,
  },
  archivePreviewList: {
    gap: 10,
  },
  archivePreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  archivePreviewFormat: {
    width: 74,
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
  },
  archivePreviewText: {
    flex: 1,
    color: '#f6fbff',
    fontSize: 13,
  },
  archivePreviewCount: {
    color: 'rgba(214,229,238,0.72)',
    fontSize: 12,
    fontWeight: '700',
  },
  settingsContent: {
    paddingBottom: 28,
  },
  settingsPanel: {
    borderRadius: 28,
    padding: 18,
    backgroundColor: 'rgba(10, 19, 28, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
    marginBottom: 14,
  },
  settingsSectionTitle: {
    color: '#f6fbff',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  settingsHint: {
    color: 'rgba(214,229,238,0.76)',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  inputLabel: {
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 8,
  },
  textInput: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: '#f6fbff',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(191, 226, 243, 0.10)',
    marginBottom: 14,
  },
  configTextInput: {
    minHeight: 220,
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 18,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  settingTextWrap: {
    flex: 1,
  },
  settingLabel: {
    color: '#f6fbff',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  settingDescription: {
    color: 'rgba(214,229,238,0.72)',
    fontSize: 12,
    lineHeight: 18,
  },
  codePreview: {
    color: '#dff9ee',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'monospace',
    backgroundColor: 'rgba(6, 15, 12, 0.86)',
    borderRadius: 18,
    padding: 14,
    overflow: 'hidden',
  },
  storageStatusRow: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
    gap: 6,
  },
  storageStatusLabel: {
    color: '#7ef2ca',
    fontSize: 11,
    fontWeight: '800',
  },
  storageStatusValue: {
    color: '#eef9ff',
    fontSize: 13,
    lineHeight: 18,
  },
  storageStatusValueError: {
    color: '#ffb3b3',
  },
  exportStatusText: {
    color: 'rgba(214,229,238,0.76)',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
});
